# Generated by Django 3.2.12 on 2022-03-16 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=45, verbose_name='Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=40, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=20, verbose_name='Color')),
                ('color_code', models.CharField(default='#000000', max_length=7, verbose_name='Color Code')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Product name')),
                ('descriptioin', models.TextField(verbose_name='Product descritption')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('size', models.CharField(max_length=100, verbose_name='Sizes')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
                ('image', models.ImageField(upload_to='product-photos/$Y/$m/$d')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.color')),
            ],
        ),
    ]
