# Generated by Django 3.2.12 on 2022-03-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220316_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default=None, max_length=45, unique=True, verbose_name='Url'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=None, max_length=40, unique=True, verbose_name='Url'),
        ),
        migrations.AddField(
            model_name='color',
            name='slug',
            field=models.SlugField(default=None, max_length=20, unique=True, verbose_name='Url'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=None, max_length=100, unique=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sizes'),
        ),
    ]
