# Generated by Django 3.2.12 on 2022-07-24 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20220323_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(default='product-photos/default.jpg', upload_to='product-photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='product-photos/default.jpg', upload_to='product-photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(default='product-photos/default.jpg', upload_to='product-photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_core',
            field=models.ImageField(default='product-photos/default.jpg', upload_to='product-photos/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=40, verbose_name='Sub Category')),
                ('slug', models.SlugField(default=None, max_length=40, unique=True, verbose_name='Url')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.category')),
            ],
            options={
                'verbose_name_plural': 'Sub categories',
            },
        ),
    ]
