# Generated by Django 3.2.12 on 2022-07-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_core',
            new_name='image',
        ),
    ]
