# Generated by Django 3.2.12 on 2022-07-30 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_image_core_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descriptioin',
            new_name='description',
        ),
    ]
